/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\Users\bayes\FitnessAnimReactV3\my-expo-app\app\assets\air-squat.glb --types --output air-squat-component.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|mixamo.com|Layer0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Maria_J_J_Ong: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    maria_M1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/air-squat.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Maria_J_J_Ong" geometry={nodes.Maria_J_J_Ong.geometry} material={materials.maria_M1} skeleton={nodes.Maria_J_J_Ong.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/air-squat.glb')
